let products = [
    {
        id: 1,
        subject: "Math",
        location: "Hendon",
        price: 19,
        image: "pictures/Math.png",
        availableInventory : 5,
        spaces: 5,
    },
    {
        id: 2,
        subject: "Football",
        location: "Hendon",
        price: 47,
        image: "pictures/Football.png",
        availableInventory: 5,
        spaces: 5,
    },
    {
        id: 3,
        subject: "Gym",
        location: "Hendon",
        price: 55,
        image: "pictures/Gym.png",
        availableInventory: 5,
        spaces: 5,
    },
    {
        id: 4,
        subject: "Physics",
        location: "Hendon",
        price: 13,
        image: "pictures/Physics.png",
        availableInventory: 5,
        spaces: 5,
    },
    {
        id: 5,
        subject: "Geography",
        location: "Hendon",
        price: 18,
        image: "pictures/Geography.png",
        availableInventory: 5,
        spaces: 5,
    },
    {
        id: 6,
        subject: "Tennis",
        location: "Hendon",
        price: 50,
        image: "pictures/Tennis.png",
        availableInventory: 5,
        spaces: 5,
    },
    {
        id: 7,
        subject: "Dance",
        location: "Hendon",
        price: 30,
        image: "pictures/Dance.png",
        availableInventory: 5,
        spaces: 5,
    },
    {
        id: 8,
        subject: "History",
        location: "Hendon",
        price: 15,
        image: "pictures/History.png",
        availableInventory: 5,
        spaces: 5,
    },
    {
        id: 9,
        subject: "Biology",
        location: "Hendon",
        price:27,
        image: "pictures/Biology.png",
        availableInventory : 5,
        spaces: 5,
    },
    {
        id: 10,
        subject: "Chemistry",
        location: "Hendon",
        price: 21,
        image: "pictures/Chemistry.png",
        availableInventory : 5,
        spaces: 5,
    },

]