let products = [
    {
        id: 1,
        subject: "Math",
        location: "Hendon",
        price: 19,
        image: "pictures/Math.png",
        availableInventory : 12,
        spaces: 12,
    },
    {
        id: 2,
        subject: "Football",
        location: "Hendon",
        price: 50,
        image: "pictures/Football.png",
        availableInventory: 21,
        spaces: 21,
    },
    {
        id: 3,
        subject: "Gym",
        location: "Hendon",
        price: 50,
        image: "pictures/Gym.png",
        availableInventory: 25,
        spaces: 25,
    },
    {
        id: 4,
        subject: "Physics",
        location: "Hendon",
        price: 17,
        image: "pictures/Physics.png",
        availableInventory: 22,
        spaces: 22,
    },
    {
        id: 5,
        subject: "Geography",
        location: "Hendon",
        price: 18,
        image: "pictures/Geography.png",
        availableInventory: 20,
        spaces: 20,
    },
    {
        id: 6,
        subject: "Tennis",
        location: "Hendon",
        price: 50,
        image: "pictures/Tennis.png",
        availableInventory: 8,
        spaces: 8,
    },
    {
        id: 7,
        subject: "Dance",
        location: "Hendon",
        price: 30,
        image: "pictures/Dance.png",
        availableInventory: 18,
        spaces: 18,
    },
    {
        id: 8,
        subject: "History",
        location: "Hendon",
        price: 15,
        image: "pictures/History.png",
        availableInventory: 13,
        spaces: 13,
    },
    {
        id: 9,
        subject: "Biology",
        location: "Hendon",
        price: 15,
        image: "pictures/Biology.png",
        availableInventory : 17,
        spaces: 17,
    },
    {
        id: 10,
        subject: "Chemistry",
        location: "Hendon",
        price: 15,
        image: "pictures/Chemistry.png",
        availableInventory : 20,
        spaces: 20,
    },

]